export { default as Avatar1 } from "./Avatar1.png";
export { default as Avatar2 } from "./Avatar2.png";
export { default as Avatar3 } from "./Avatar3.png";
export { default as Avatar4 } from "./Avatar4.png";
export { default as Avatar5 } from "./Avatar5.png";
export { default as Avatar6 } from "./Avatar6.png";
export { default as Avatar7 } from "./Avatar7.png";
export { default as Avatar8 } from "./Avatar8.png";
export { default as LoginHero } from "./LoginHero.png";